js-service: add extensions for nextjs support
fleek-network/lightning pull request #47
Opened 2024-10-17 22:45 UTC by kckeiks

2024-10-17 23:32 UTC, ozwaldorf requested changes

2024-10-17 23:32 UTC, ozwaldorf commented on services/js-poc/deno_fleek/src/extension.rs
> +        op_napi_open<P>
minor nit, it might even be worth just moving the shim stuff into its own adjacent crate/extension so we dont clutter our real runtime opcode impls in the corresponding ops.rs file

2024-10-17 23:32 UTC, ozwaldorf commented on services/js-poc/deno_fleek/src/ops.rs
> +    NP: NapiPermissions + 'static,
can remove the generic i think as per above comment on removing deno_napi dependency
```suggestion
#[op2(reentrant)]
pub fn op_napi_open<'scope>(
    _scope: &mut v8::HandleScope<'scope>,
    _isolate: *mut v8::Isolate,
    _op_state: Rc<RefCell<OpState>>,
    #[string] _path: String,
    _global: v8::Local<'scope, v8::Object>,
    _buffer_constructor: v8::Local<'scope, v8::Function>,
    _report_error: v8::Local<'scope, v8::Function>,
) -> std::result::Result<v8::Local<'scope, v8::Value>, AnyError>
```

2024-10-17 23:32 UTC, ozwaldorf commented on services/js-poc/deno_fleek/Cargo.toml
> +log = "0.4"
why log over tracing? We already use tracing in the service itself, as well as the node

2024-10-17 23:32 UTC, ozwaldorf commented on services/js-poc/src/runtime/mod.rs
> +                    MaybeArc::new(InMemoryFs::default()),
Should reuse the same InMemoryFs here

2024-10-17 23:32 UTC, ozwaldorf commented on services/js-poc/build.rs
> +        ),
same here reuse the same inmemoryfs for consenstency. Though not as crucial as it's never used for snapshotting

2024-10-17 23:32 UTC, ozwaldorf commented on services/js-poc/build.rs
> +    println!("cargo::rerun-if-changed=./ext/node/polyfill/deno.lock");
Can remove along with comment

2024-10-17 23:33 UTC, ozwaldorf commented
some unsolicited review :+1:

2024-10-18 09:36 UTC, kckeiks commented on services/js-poc/deno_fleek/Cargo.toml
> +deno_websocket = "0.169"
This is a draft so will clean up when opening it for review.

2024-10-18 09:36 UTC, kckeiks commented on services/js-poc/deno_fleek/src/extension.rs
> +    parameters = [P: NapiPermissions],
same as above

2024-10-18 09:38 UTC, kckeiks commented
> some unsolicited review 😄

This is a draft (as per the status). I will clean it up later after testing which will address your nits.

2024-10-20 22:48 UTC, kckeiks commented on services/js-poc/deno_fleek/Cargo.toml
> +deno_websocket = "0.169"
Most of these 

> Pretty much all of these are unused, we only actually use them in runtime/mod.rs and build.rs which is outside of this crate

No, we don't. Pretty much all of these had to stay.

2024-10-20 22:50 UTC, kckeiks commented on services/js-poc/deno_fleek/src/extension.rs
> +        op_napi_open<P>
I don't think it's needed, at least not in the moment when most are noop.

2024-10-20 22:55 UTC, kckeiks commented on services/js-poc/deno_fleek/Cargo.toml
> +log = "0.4"
No real reason, I was copying and pasting and getting the core of the solution implemented...as mentioned before this is a draft.

2024-10-21 00:09 UTC, ozwaldorf commented on services/js-poc/deno_fleek/Cargo.toml
> +deno_websocket = "0.169"
Ahh for the permissions!

It might be more maintainable (in terms of upgrading deno deps) to just impl the permissions in the service side where we put the runtime together, that way we dont have to match the dep versions across multiple files when upgrading the services runtime

2024-10-21 00:11 UTC, ozwaldorf commented on services/js-poc/deno_fleek/src/extension.rs
> +        op_napi_open<P>
Fair 👍 I was mostly just concerned about having a clear separation between our own runtime ops

2024-10-21 11:42 UTC, kckeiks commented on services/js-poc/deno_fleek/Cargo.toml
> +deno_websocket = "0.169"
We might as well make them workspace dependencies then because there might be cases where we might need them in the future in this crate.

2024-10-21 12:36 UTC, ozwaldorf commented on services/js-poc/deno_fleek/Cargo.toml
> +deno_websocket = "0.169"
Do you think we should make the service it's own workspace in this case? The sgx service already is for example

2024-10-21 13:44 UTC, kckeiks commented on services/js-poc/deno_fleek/Cargo.toml
> +deno_websocket = "0.169"
Yes, that makes sense. We should discuss the organization of these services soon when we have a moment and implement it on a separate PR.

2024-10-23 16:02 UTC, merged